# Generated by Django 5.1.2 on 2024-10-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14)),
                ('cargo', models.IntegerField(choices=[(0, 'Admin'), (1, 'Tech Leader'), (2, 'Instrutor'), (3, 'Veterano'), (4, 'Novato'), (5, 'Imersionista')], default=5)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
