# Generated by Django 5.1.2 on 2024-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='curso',
            field=models.CharField(choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('CC', 'Ciência da Computação'), ('SI', 'Sistemas para Internet'), ('CD', 'Ciência de Dados'), ('OTR', 'Outros')], max_length=40, verbose_name='Curso'),
        ),
    ]
