# Generated by Django 5.1.2 on 2024-10-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuarios_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ingresso_inst',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='sexo',
        ),
    ]
