# Generated by Django 5.1.2 on 2024-11-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuarios_data_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email_institucional',
            field=models.EmailField(default=0, max_length=254, unique=True, verbose_name='Email Institucional'),
            preserve_default=False,
        ),
    ]
