# Generated by Django 5.1.2 on 2024-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuarios_email_institucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número de Telefone'),
        ),
    ]
