# Generated by Django 5.1.7 on 2025-04-25 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0008_participante_rgm_excecao_extensionistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área da Fábrica',
                'verbose_name_plural': 'Áreas da Fábrica',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.CreateModel(
            name='Imersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Imersão',
                'verbose_name_plural': 'Imersões',
                'unique_together': {('ano', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='FormularioInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(auto_now_add=True, help_text='Data em que o participante se inscreveu na imersão')),
                ('participante', models.ForeignKey(help_text='Participante que preencheu o formulário', on_delete=django.db.models.deletion.CASCADE, to='api_rest.participante')),
                ('primeira_opcao', models.ForeignKey(help_text='Primeira opção de vaga que o participante deseja', on_delete=django.db.models.deletion.CASCADE, related_name='primeira_opcao_forms', to='imersao.areafabrica')),
                ('segunda_opcao', models.ForeignKey(help_text='Segunda opção de vaga que o participante deseja', on_delete=django.db.models.deletion.CASCADE, related_name='segunda_opcao_forms', to='imersao.areafabrica')),
                ('imersao', models.ForeignKey(help_text='Imersão a qual o participante se inscreveu', on_delete=django.db.models.deletion.CASCADE, to='imersao.imersao')),
                ('tecnologias', models.ManyToManyField(help_text='Tecnologias que o participante tem interesse', to='imersao.tecnologia')),
            ],
            options={
                'verbose_name': 'Formulário de Inscrição',
                'verbose_name_plural': 'Formulários de Inscrição',
                'unique_together': {('participante', 'imersao')},
            },
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('palestrante', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('bloco', models.CharField(max_length=10)),
                ('imersao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.imersao')),
            ],
            options={
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestras',
                'unique_together': {('imersao', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('instrutor', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('bloco', models.CharField(max_length=2)),
                ('imersao', models.ForeignKey(help_text='Imersão a qual o workshop pertence', on_delete=django.db.models.deletion.CASCADE, to='imersao.imersao')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'unique_together': {('imersao', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='DiaWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('conteudo', models.CharField(max_length=255)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='imersao.workshop')),
            ],
            options={
                'verbose_name': 'Dia de Workshop',
                'verbose_name_plural': 'Dias de Workshop',
                'unique_together': {('workshop', 'data')},
            },
        ),
        migrations.CreateModel(
            name='InteresseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(help_text='Nível de interesse na área entre 0 e 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.areafabrica')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='imersao.formularioinscricao')),
            ],
            options={
                'verbose_name': 'Interesse por Área',
                'verbose_name_plural': 'Interesses por Área',
                'unique_together': {('formulario', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoImersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_participacao', models.DateField(auto_now_add=True)),
                ('imersao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.imersao')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.participante')),
            ],
            options={
                'verbose_name': 'Participação na Imersão',
                'verbose_name_plural': 'Participações na Imersão',
                'unique_together': {('participante', 'imersao')},
            },
        ),
        migrations.CreateModel(
            name='PresencaPalestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_participacao', models.DateField(auto_now_add=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.palestra')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.participante')),
            ],
            options={
                'verbose_name': 'Presença na Palestra',
                'verbose_name_plural': 'Presenças na Palestra',
                'unique_together': {('participante', 'palestra')},
            },
        ),
        migrations.CreateModel(
            name='PresencaWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('dia_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.diaworkshop')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.participante')),
            ],
            options={
                'verbose_name': 'Presença no Workshop',
                'verbose_name_plural': 'Presenças no Workshop',
                'unique_together': {('participante', 'dia_workshop')},
            },
        ),
        migrations.CreateModel(
            name='DesempenhoWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('classificacao', models.CharField(max_length=255)),
                ('experiencia', models.CharField(max_length=255)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidades', to='imersao.areafabrica')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.participante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imersao.workshop')),
            ],
            options={
                'verbose_name': 'Desempenho no Workshop',
                'verbose_name_plural': 'Desempenhos nos Workshops',
                'unique_together': {('participante', 'workshop')},
            },
        ),
    ]
