# Generated by Django 5.1.7 on 2025-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
