# Generated by Django 5.2 on 2025-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteracao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
