# Generated by Django 5.2 on 2025-07-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Email Autorizado de Administradores',
                'verbose_name_plural': 'Emails Autorizados de Administradores',
                'permissions': [('ver_emails_autorizados_admins', 'Ver todos os Emails Autorizados de Administradores'), ('editar_emails_autorizados_admins', 'Editar todos os Emails Autorizados de Administradores')],
            },
        ),
        migrations.CreateModel(
            name='EmailsFixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Email Autorizado de Membros',
                'verbose_name_plural': 'Emails Autorizados de Membros',
                'permissions': [('ver_emails_autorizados_membros', 'Ver todos os Emails Autorizados de Membros'), ('editar_emails_autorizados_membros', 'Editar todos os Emails Autorizados de Membros')],
            },
        ),
        migrations.CreateModel(
            name='EmailsParticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('iteracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imersao.iteracao')),
            ],
            options={
                'verbose_name': 'Email Autorizado de Participante',
                'verbose_name_plural': 'Emails Autorizados de Participantes',
                'permissions': [('ver_emails_autorizados_participantes', 'Ver todos os Emails Autorizados de Participantes'), ('editar_emails_autorizados_participantes', 'Editar todos os Emails Autorizados de Participantes')],
                'unique_together': {('email', 'iteracao')},
            },
        ),
    ]
