# Generated by Django 5.2 on 2025-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0002_alter_iteracao_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areafabrica',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
