# Generated by Django 5.1.7 on 2025-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0002_tecnologia_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='bloco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='sala',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
