# Generated by Django 5.2 on 2025-06-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0021_alter_techleader_especialidade'),
        ('imersao', '0003_alter_areafabrica_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='bloco',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='sala',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DesafioWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafio_participante', to='api_rest.participante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafio_workshop', to='imersao.workshop')),
            ],
            options={
                'verbose_name': 'Desafio do workshop',
                'verbose_name_plural': 'Desafios dos workshops',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
