# Generated by Django 5.2 on 2025-04-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_alter_excecao_options_extensionista_and_more'),
        ('imersao', '0003_alter_palestra_bloco_alter_palestra_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='instrutor',
        ),
        migrations.AddField(
            model_name='desempenhoworkshop',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='desempenhoworkshop',
            name='especialidade',
            field=models.ForeignKey(blank=True, help_text='Tecnologia que o participante se destacou no workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialidade_desempenho', to='imersao.tecnologia'),
        ),
        migrations.AlterField(
            model_name='desempenhoworkshop',
            name='participante',
            field=models.ForeignKey(help_text='Participante que teve seu desempenho avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='desempenho_workshops', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='desempenhoworkshop',
            name='workshop',
            field=models.ForeignKey(help_text='Workshop ao qual o desempenho se refere', on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos_workshop', to='imersao.workshop'),
        ),
        migrations.AlterField(
            model_name='diaworkshop',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_workshop', to='imersao.workshop'),
        ),
        migrations.AlterField(
            model_name='formularioinscricao',
            name='imersao',
            field=models.ForeignKey(help_text='Imersão a qual o participante se inscreveu', on_delete=django.db.models.deletion.CASCADE, related_name='formularios_imersao', to='imersao.imersao'),
        ),
        migrations.AlterField(
            model_name='formularioinscricao',
            name='participante',
            field=models.ForeignKey(help_text='Participante que preencheu o formulário', on_delete=django.db.models.deletion.CASCADE, related_name='formularios_participante', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='interessearea',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_forms', to='imersao.formularioinscricao'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='imersao',
            field=models.ForeignKey(help_text='Imersão a qual a palestra pertence', on_delete=django.db.models.deletion.CASCADE, related_name='palestras_imersao', to='imersao.imersao'),
        ),
        migrations.AlterField(
            model_name='participacaoimersao',
            name='imersao',
            field=models.ForeignKey(help_text='Imersão na qual o participante participou', on_delete=django.db.models.deletion.CASCADE, related_name='participantes_imersao', to='imersao.imersao'),
        ),
        migrations.AlterField(
            model_name='participacaoimersao',
            name='participante',
            field=models.ForeignKey(help_text='Participante que participou da imersão', on_delete=django.db.models.deletion.CASCADE, related_name='imersoes_participadas', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='presencapalestra',
            name='palestra',
            field=models.ForeignKey(help_text='Palestra na qual o participante participou', on_delete=django.db.models.deletion.CASCADE, related_name='participantes_palestra', to='imersao.palestra'),
        ),
        migrations.AlterField(
            model_name='presencapalestra',
            name='participante',
            field=models.ForeignKey(help_text='Participante que participou da palestra', on_delete=django.db.models.deletion.CASCADE, related_name='palestras_participadas', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='presencaworkshop',
            name='dia_workshop',
            field=models.ForeignKey(help_text='Dia do workshop no qual o participante participou', on_delete=django.db.models.deletion.CASCADE, related_name='participantes_dia_workshop', to='imersao.diaworkshop'),
        ),
        migrations.AlterField(
            model_name='presencaworkshop',
            name='participante',
            field=models.ForeignKey(help_text='Participante que participou do workshop', on_delete=django.db.models.deletion.CASCADE, related_name='workshops_participados', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='imersao',
            field=models.ForeignKey(help_text='Imersão a qual o workshop pertence', on_delete=django.db.models.deletion.CASCADE, related_name='workshops_imersao', to='imersao.imersao'),
        ),
        migrations.CreateModel(
            name='InstrutorWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionista', models.ForeignKey(help_text='Extensionista que é instrutor do workshop', on_delete=django.db.models.deletion.CASCADE, related_name='workshop_instruidos', to='api_rest.extensionista')),
                ('workshop', models.ForeignKey(help_text='Workshop ao qual o instrutor pertence', on_delete=django.db.models.deletion.CASCADE, related_name='instrutores_workshop', to='imersao.workshop')),
            ],
            options={
                'verbose_name': 'Instrutor do Workshop',
                'verbose_name_plural': 'Instrutores do Workshop',
                'unique_together': {('workshop', 'extensionista')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantesWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.ForeignKey(help_text='Participante inscrito no workshop', on_delete=django.db.models.deletion.CASCADE, related_name='workshops_participante', to='api_rest.participante')),
                ('workshop', models.ForeignKey(help_text='Workshop ao qual o participante está inscrito', on_delete=django.db.models.deletion.CASCADE, related_name='participantes_workshop', to='imersao.workshop')),
            ],
            options={
                'verbose_name': 'Participação no Workshop',
                'verbose_name_plural': 'Participações no Workshop',
                'unique_together': {('participante', 'workshop')},
            },
        ),
    ]
