# Generated by Django 5.2 on 2025-05-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0004_remove_workshop_instrutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imersao',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imersao',
            name='data_inicio',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
