# Generated by Django 5.2 on 2025-06-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0004_alter_workshop_unique_together_alter_workshop_bloco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaworkshop',
            name='conteudo',
        ),
    ]
