# Generated by Django 5.2 on 2025-06-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0005_remove_diaworkshop_conteudo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workshop',
            unique_together={('iteracao', 'titulo')},
        ),
    ]
