# Generated by Django 5.2 on 2025-06-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0006_alter_workshop_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinscricao',
            name='tecnologias',
            field=models.ManyToManyField(help_text='Tecnologias que o participante tem interesse', related_name='tecnologias_forms', to='imersao.tecnologia'),
        ),
    ]
