# Generated by Django 5.2 on 2025-07-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0007_alter_formularioinscricao_tecnologias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areafabrica',
            options={'permissions': [('ver_areas_fabrica', 'Ver todas as Áreas da Fábrica'), ('editar_areas_fabrica', 'Editar todas as Áreas da Fábrica')], 'verbose_name': 'Área da Fábrica', 'verbose_name_plural': 'Áreas da Fábrica'},
        ),
        migrations.AlterModelOptions(
            name='desafioworkshop',
            options={'managed': True, 'permissions': [('ver_desafios_workshop', 'Ver todos os Desafios dos workshops'), ('editar_desafios_workshop', 'Editar todos os Desafios dos workshops')], 'verbose_name': 'Desafio do workshop', 'verbose_name_plural': 'Desafios dos workshops'},
        ),
        migrations.AlterModelOptions(
            name='desempenhoworkshop',
            options={'permissions': [('ver_desempenhos_workshops', 'Ver todos os Desempenhos nos Workshops'), ('editar_desempenhos_workshops', 'Editar todos os Desempenhos nos Workshops')], 'verbose_name': 'Desempenho no Workshop', 'verbose_name_plural': 'Desempenhos nos Workshops'},
        ),
        migrations.AlterModelOptions(
            name='diaworkshop',
            options={'permissions': [('ver_dias_workshops', 'Ver todos os Dias de Workshop'), ('editar_dias_workshops', 'Editar todos os Dias de Workshop')], 'verbose_name': 'Dia de Workshop', 'verbose_name_plural': 'Dias de Workshop'},
        ),
        migrations.AlterModelOptions(
            name='formularioinscricao',
            options={'permissions': [('ver_formularios_workshop', 'Ver todas as Formulários de Inscrição'), ('editar_formularios_workshop', 'Editar todas as Formulários de Inscrição')], 'verbose_name': 'Formulário de Inscrição', 'verbose_name_plural': 'Formulários de Inscrição'},
        ),
        migrations.AlterModelOptions(
            name='imersao',
            options={'permissions': [('ver_imersoes', 'Ver todas as imersões'), ('editar_imersoes', 'Editar todas as imersões')], 'verbose_name': 'Imersão', 'verbose_name_plural': 'Imersões'},
        ),
        migrations.AlterModelOptions(
            name='instrutorworkshop',
            options={'permissions': [('ver_instrutores_workshops', 'Ver todos os Instrutores do Workshop'), ('editar_instrutores_workshops', 'Editar todos os Instrutores do Workshop')], 'verbose_name': 'Instrutor do Workshop', 'verbose_name_plural': 'Instrutores do Workshop'},
        ),
        migrations.AlterModelOptions(
            name='interessearea',
            options={'permissions': [('ver_interesses_area', 'Ver todas as Interesses por Área'), ('editar_interesses_area', 'Editar todas as Interesses por Área')], 'verbose_name': 'Interesse por Área', 'verbose_name_plural': 'Interesses por Área'},
        ),
        migrations.AlterModelOptions(
            name='iteracao',
            options={'permissions': [('ver_iteracoes', 'Ver todas as iterações'), ('editar_iteracoes', 'Editar todas as iterações')], 'verbose_name': 'Iteração', 'verbose_name_plural': 'Iterações'},
        ),
        migrations.AlterModelOptions(
            name='palestra',
            options={'permissions': [('ver_palestras', 'Ver todas as Palestras'), ('editar_palestras', 'Editar todas as Palestras')], 'verbose_name': 'Palestra', 'verbose_name_plural': 'Palestras'},
        ),
        migrations.AlterModelOptions(
            name='participacaoimersao',
            options={'permissions': [('ver_participacoes_imersao', 'Ver todos os Participações na Imersão'), ('editar_participacoes_imersao', 'Editar todos os Participações na Imersão')], 'verbose_name': 'Participação na Imersão', 'verbose_name_plural': 'Participações na Imersão'},
        ),
        migrations.AlterModelOptions(
            name='participantesworkshop',
            options={'permissions': [('ver_participantes_workshop', 'Ver todos os Desafios dos workshops'), ('editar_participantes_workshop', 'Editar todos os Desafios dos workshops')], 'verbose_name': 'Participação no Workshop', 'verbose_name_plural': 'Participações no Workshop'},
        ),
        migrations.AlterModelOptions(
            name='presencapalestra',
            options={'permissions': [('ver_presencas_palestras', 'Ver todos os Presenças na Palestra'), ('editar_presencas_palestras', 'Editar todos os Presenças na Palestra')], 'verbose_name': 'Presença na Palestra', 'verbose_name_plural': 'Presenças na Palestra'},
        ),
        migrations.AlterModelOptions(
            name='presencaworkshop',
            options={'permissions': [('ver_presencas_workshops', 'Ver todas as Presenças nos Workshops'), ('editar_presencas_workshops', 'Editar todas as Presenças nos Workshops')], 'verbose_name': 'Presença no Workshop', 'verbose_name_plural': 'Presenças no Workshop'},
        ),
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'permissions': [('ver_tecnologia', 'Ver todas as Tecnologias'), ('editar_tecnologia', 'Editar todas as Tecnologias')], 'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'permissions': [('ver_workshops', 'Ver todas as Workshops'), ('editar_workshop', 'Editar todas as Workshops')], 'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
    ]
