
###
POST {{url_raiz}}{{url_login}} HTTP/1.1
Content-Type: application/json

{
    "username": "{{admin_username}}",
    "password": "{{admin_password}}"
}

###
POST {{url_raiz}}{{url_CREATE_usuarios}} HTTP/1.1
Content-Type: application/json

{
    "perfil": "{{perfil_admin}}",
    "nome": "{{admin_nome}}",
    "username": "{{admin_username}}",
    "password": "{{admin_password}}"
}

###
POST {{url_raiz}}{{url_CREATE_usuarios}} HTTP/1.1
Content-Type: application/json

{
    "perfil": "admin"
}
