###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "teste@teste.com",
    "password": "teste"
}

###
POST http://localhost:8000/api/auth/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{refresh_token}}"
}

###
POST http://localhost:8000/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "refresh_token": "{{refresh_token}}"
}

###
GET http://localhost:8000/api/participante/ HTTP/1.1

###
GET http://localhost:8000/api/participante/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/participante/1 HTTP/1.1
Authorization: Bearer {{access_token}}

###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "qparticipantes@exemplo.com",
    "password": "senha123"
}

###
POST http://localhost:8000/api/participante/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "qExemplos Participantes",
        "username": "qparticipantes@exemplo.com",
        "password": "senha123",
        "telefone": "11998999999"
    },
    "cpf": "90000000001",
    "curso": "ADS",
    "outro_curso": "",
    "periodo": "4",
    "email_institucional": "qnovos@exemplo.com.br"
}

###
PUT http://localhost:8000/api/participante/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "nome": "Particiate Atualizado",
        "username": "participantes@exemplo.com",
        "password": "teste",
        "telefone": "11999999999"
    },
    "cpf": "12345678902",
    "curso": "CC",
    "email_institucional": "novo@fatec.sp.gov.br"
}


###
PUT http://localhost:8000/api/participante/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "id": 3,
        "nome": "Novo Atual",
        "username": "novo@participante.com",
        "telefone": "11999999999"
    },
    "cpf": "12345678902",
    "curso": "CC",
    "email_institucional": "novo@fatec.sp.gov.br"
}
###

PATCH http://localhost:8000/api/participante/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "username": "testudo@teste.com"
    },
    "curso": "ADS"
}

###

DELETE http://localhost:8000/api/participante/1/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET http://localhost:8000/api/empresa/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

POST http://localhost:8000/api/empresa/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "3eNova Empresa",
        "username": "3econtato@empresa.com",
        "password": "senhaEmpresa!",
        "telefone": "1133333333"
    },
    "cnpj": "32345678000199",
    "representante": "Carlos Andrade"
}

###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "contato@empresa.com",
        "password": "senhaEmpresa!"
}
###

PUT http://localhost:8000/api/empresa/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "nome": "Empresa Atualizada",
        "username": "contato@empresa.com",
        "password": "novaSenhaEmpresa!",
        "telefone": "1144444444"
    },
    "cnpj": "12345678000199",
    "representante": "Ana Pereira"
}

###

PATCH http://localhost:8000/api/empresa/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "representante": "João Souza"
}

###

# 5.6 Deletar Empresa
DELETE http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
POST http://localhost:8000/api/techleader/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Novo TechLeader",
        "username": "tech@leader.com",
        "password": "senhaTech!",
        "telefone": "1155555555"
    },
    "codigo": "9999",
    "especialidade": "Backend"
}

###
PUT http://localhost:8000/api/techleader/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "nome": "TechLeader Atualizado",
        "username": "tech@leader.com",
        "password": "novaSenhaTech!",
        "telefone": "1166666666"
    },
    "codigo": "9999",
    "especialidade": "Fullstack"
}

###
PATCH http://localhost:8000/api/techleader/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "especialidade": "DevOps"
}

###
DELETE http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}
