###
POST https://f360-latest.onrender.com/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin@exsample.com",
    "password": "senhaSupesrSegura123"
}

###
POST https://f360-latest.onrender.com/api/criar-admin/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Administrador Geral",
    "username": "admin@exsample.com",
    "password": "senhaSupesrSegura123"
}

###
POST http://localhost:8000/api/auth/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{refresh_token}}"
}

###
POST http://localhost:8000/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "refresh_token": "{{refresh_token}}"
}

###
GET http://localhost:8000/api/participante/ HTTP/1.1

###
GET http://localhost:8000/api/participante/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MTUwNTkyLCJpYXQiOjE3NDYxNDg3OTIsImp0aSI6IjllNDc3NzA0ZGU2NDQyNDhhZTgxN2ZiYzYwZjdhODkxIiwidXNlcl9pZCI6MjEsIm5vbWUiOiJBZG1pbmlzdHJhZG9yIEdlcmFsIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInRpcG9fdXN1YXJpbyI6IkFETUlOIn0.n1WUnlhasb9xh-UpIpkFXBK2IKoZIL2AqlvxEyjtUsQ

###
GET http://localhost:8000/api/participante/789 HTTP/1.1


###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "qparticipantes@exemplo.com",
    "password": "senha123"
}

###
POST http://localhost:8000/api/participante/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "João Silva",
        "username": "joadwdfgfodfg@email.com",
        "password": "senha123",
        "telefone": "11907054321"
    },
    "cpf": "10325978981",
    "rgm": "15398348",
    "curso": "ADS",
    "outro_curso": "",
    "periodo": 3,
    "email_institucional": "joao.sdisdfsva@al0n3o.edu.br"
}


###
DELETE http://localhost:8000/api/participante/3/ HTTP/1.1

###
PUT http://localhost:8000/api/participante/14/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "João Silva",
        "username": "joadwdfgfodfg@email.com",
        "password": "senha123",
        "telefone": "11907054321"
    },
    "cpf": "10325978981",
    "rgm": "15398348",
    "curso": "ADS",
    "outro_curso": "",
    "periodo": 3,
    "email_institucional": "joao.sdisdfsva@al0n3o.edu.br"
}


###
PUT http://localhost:8000/api/participante/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "id": 3,
        "nome": "Novo Atual",
        "username": "novo@participante.com",
        "telefone": "11999999999"
    },
    "cpf": "12345678902",
    "curso": "CC",
    "email_institucional": "novo@fatec.sp.gov.br"
}
###
PATCH http://localhost:8000/api/participante/14/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "João Silva",
        "username": "joadwdfgfodfg@email.com",
        "password": "senha123",
        "telefone": "11907054321"
    },
    "cpf": "10325978981",
    "rgm": "15398348",
    "curso": "ADS",
    "outro_curso": "",
    "periodo": 3,
    "email_institucional": "joao.sdisdfsva@al0n3o.edu.br"
}

###
DELETE http://localhost:8000/api/participante/1/ HTTP/1.1


DELETE http://localhost:8000/api/participante/1/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET http://localhost:8000/api/empresa/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

POST http://localhost:8000/api/empresa/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "string",
        "username": "user@example.com",
        "password": "string",
        "telefone": "string"
    },
    "cnpj": "99530743935341",
    "representante": "string"
}

###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "contato@empresa.com",
        "password": "senhaEmpresa!"
}
###

PUT http://localhost:8000/api/empresa/1/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "string",
        "username": "usesr@example.com",
        "password": "string",
        "telefone": "string"
    },
    "cnpj": "99530743935341",
    "representante": "string"
}

###

PATCH http://localhost:8000/api/empresa/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "representante": "João Souza"
}

###

# 5.6 Deletar Empresa
DELETE http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
POST http://localhost:8000/api/techleader/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Novo TechLeader",
        "username": "tecdh@leasdfader.com",
        "password": "senhaTech!",
        "telefone": "1155555555"
    },
    "codigo": "991234939",
    "especialidade": "Backend"
}

###
GET http://localhost:8000/api/techleader/346/

###
PUT http://localhost:8000/api/techleader/3/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Novo TechLeader",
        "username": "tecdh@leasdfader.com",
        "password": "senhaTech!",
        "telefone": "1155555555"
    },
    "codigo": "991234939",
    "especialidade": "Backend"
}

###
PATCH http://localhost:8000/api/techleader/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "especialidade": "DevOps"
}

###
DELETE http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}



############################################################################




###
POST http://localhost:8000/api/imersao/ HTTP/1.1
Content-Type: application/json

{
    "ano": 2025,
    "semestre": 1
}

###
GET http://localhost:8000/api/imersao/ HTTP/1.1

###
GET http://localhost:8000/api/imersao/1 HTTP/1.1

###
POST http://localhost:8000/api/area_fabrica/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Backend",
    "ativa": "true"
}
###
POST http://localhost:8000/api/area_fabrica/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Frontend",
    "ativa": "true"
}

###
POST http://localhost:8000/api/area_fabrica/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Dados",
    "ativa": "true"
}

###
GET http://localhost:8000/api/area_fabrica/ HTTP/1.1


###
POST http://localhost:8000/api/tecnologia/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Python",
    "ativa": "true"
}

###
POST http://localhost:8000/api/tecnologia/ HTTP/1.1
Content-Type: application/json

{
    "nome": "Django",
    "ativa": "true"
}

###
GET http://localhost:8000/api/tecnologia/ HTTP/1.1

###
POST http://localhost:8000/api/palestra/ HTTP/1.1
Content-Type: application/json

{
    "titulo": "Palestra de Teste",
    "descricao": "Descrição da palestra de teste",
    "data": "2025-01-01T10:00:00Z",
    "palestrante": "Pedro",
    "sala": "Auditório 1",
    "bloco": "A",
    "imersao": 1
}

###
GET http://localhost:8000/api/palestra/ HTTP/1.1

###
POST http://localhost:8000/api/formulario_inscricao/ HTTP/1.1
Content-Type: application/json

{
    "participante": 1,  
    "imersao": 1,      
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ]
}

###
GET http://localhost:8000/api/formulario_inscricao/3/ HTTP/1.1

###
DELETE http://localhost:8000/api/formulario_inscricao/2/ HTTP/1.1

###
GET http://localhost:8000/api/interesse_area/ HTTP/1.1

### 
POST http://localhost:8000/api/participacao_imersao/ HTTP/1.1

###
POST http://localhost:8000/api/presenca_palestra/ HTTP/1.1
Content-Type: application/json

{
    "participante": 1,
    "palestra": 1
}

###
GET http://localhost:8000/api/presenca_palestra/ HTTP/1.1