###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "teste@teste.com",
    "password": "teste"
}

###
POST http://localhost:8000/api/auth/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjAzOTk0LCJpYXQiOjE3NDUyMDIxOTQsImp0aSI6IjZkNTBlZWZmMzljYjQ3ZTU5MzI5M2M2OGEwNGIyY2ZjIiwidXNlcl9pZCI6MSwibm9tZSI6IkV4ZW1wbG9zIFBhcnRpY2lwYW50ZXMiLCJlbWFpbCI6InBhcnRpY2lwYW50ZXNAZXhlbXBsby5jb20iLCJ0aXBvX3VzdWFyaW8iOiJQQVJUIn0.M5N-Nmk9wd2O6Y8vJw6yXgpYM6wdJq2_k_Kh1sfThI8"
}

###
POST http://localhost:8000/api/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODUxNTUxLCJpYXQiOjE3NDQ4NDk3NTEsImp0aSI6IjQ3MTdmZGIzZmYwODQ0NDk4MGMyNDg4MzU0OWM5NmQxIiwidXNlcl9pZCI6Mn0.WttvRjcdi-YF9Ozdi9aiMGwifXroPvpROIgucu7hT48

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NDkzNjE1MSwiaWF0IjoxNzQ0ODQ5NzUxLCJqdGkiOiI5MTY5YTc4Y2Q5NDY0MTQyYjY1N2FiOTZmY2RiNzI2YSIsInVzZXJfaWQiOjJ9._duQgGpstXDzXgmozMIdpHKU2Iu4_4w3mbd2kecU7cM"
}

###
GET http://localhost:8000/api/participante/ HTTP/1.1

###
GET http://localhost:8000/api/participante/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjA5OTg5LCJpYXQiOjE3NDUyMDgxODksImp0aSI6ImI4YzU1ZDZhZWZjMDQ1ODBhNzBmNTBjYTc2NGY5NTM0IiwidXNlcl9pZCI6MSwibm9tZSI6IkV4ZW1wbG9zIFBhcnRpY2lwYW50ZXMiLCJlbWFpbCI6InBhcnRpY2lwYW50ZXNAZXhlbXBsby5jb20iLCJ0aXBvX3VzdWFyaW8iOiJQQVJUIn0.ioJjsuyt6Mk6AK_jvzd_rOoWpmdRudIEw19tzkXk-Gc

###
GET http://localhost:8000/api/participante/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODUyMzA0LCJpYXQiOjE3NDQ4NTA1MDQsImp0aSI6ImZjYjQ5OTQ3YjJmMTQ5NTBhMDQ5NmM0Y2YzZWM5NzFmIiwidXNlcl9pZCI6Mn0.qBP2jW8-y51Mw6nDnB60KDoVlmWwykZJ8qgb6earmgo

###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "participantes@exemplo.com",
    "password": "senha123"
}

###
POST http://localhost:8000/api/participante/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Exemplos Participantes",
        "username": "participantes@exemplo.com",
        "password": "senha123",
        "telefone": "11998999999"
    },
    "cpf": "00000000001",
    "curso": "ADS",
    "email_institucional": "novos@exemplo.com.br"
}

###
PUT http://localhost:8000/api/participante/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjA3ODA5LCJpYXQiOjE3NDUyMDYwMDksImp0aSI6ImNlNzdhMTQ3MmNkNzQyMmI4ZWFhOTkzODBmZWI3MzRmIiwidXNlcl9pZCI6MSwibm9tZSI6IkV4ZW1wbG9zIFBhcnRpY2lwYW50ZXMiLCJlbWFpbCI6InBhcnRpY2lwYW50ZXNAZXhlbXBsby5jb20iLCJ0aXBvX3VzdWFyaW8iOiJQQVJUIn0.pxO8o3BFhN1AFLy9aDAORTrZ5fu26c3-LJAjpyXP8_o

{
    "usuario": {
        "nome": "Particiate Atualizado",
        "username": "participantes@exemplo.com",
        "password": "teste",
        "telefone": "11999999999"
    },
    "cpf": "12345678902",
    "curso": "CC",
    "email_institucional": "novo@fatec.sp.gov.br"
}


###
PUT http://localhost:8000/api/participante/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODUzOTgyLCJpYXQiOjE3NDQ4NTIwNjYsImp0aSI6IjE3ZDk2MGExMzNiMTRjNDVhOTlmZTAwNmQ0YmVjZTQxIiwidXNlcl9pZCI6M30.foZmqgbyyyEsmuyU1e8kAGNs7dEKrQ5H4J6z3aqA6iU

{
    "usuario": {
        "id": 3,
        "nome": "Novo Atual",
        "username": "novo@participante.com",
        "telefone": "11999999999"
    },
    "cpf": "12345678902",
    "curso": "CC",
    "email_institucional": "novo@fatec.sp.gov.br"
}
###

PATCH http://localhost:8000/api/participante/3/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODU0MTY0LCJpYXQiOjE3NDQ4NTIwNjYsImp0aSI6IjQ5MGZjNWQwNWNiZDQ4YmM5MzM2MGQ3OWExZGYwZDQxIiwidXNlcl9pZCI6M30.4-33FZJBB6737GQlASBxQpdx12OckZD2l8YJE4Q7EwM

{
    "usuario": {
        "username": "testudo@teste.com"
    },
    "curso": "ADS"
}

###

DELETE http://localhost:8000/api/participante/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjA4NTE4LCJpYXQiOjE3NDUyMDY3MTgsImp0aSI6IjBiN2U2MTQzMjkxYTRmYTE5OGMxY2UwYzE2MWNiMTYyIiwidXNlcl9pZCI6MSwibm9tZSI6IkV4ZW1wbG9zIFBhcnRpY2lwYW50ZXMiLCJlbWFpbCI6InBhcnRpY2lwYW50ZXNAZXhlbXBsby5jb20iLCJ0aXBvX3VzdWFyaW8iOiJQQVJUIn0.x72L_2O46waimNWnuKpEiqUULD2Ckakeb0G1fUtnl3g

###

GET http://localhost:8000/api/empresa/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

GET http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###

POST http://localhost:8000/api/empresa/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Nova Empresa",
        "username": "contato@empresa.com",
        "password": "senhaEmpresa!",
        "telefone": "1133333333"
    },
    "cnpj": "12345678000199",
    "representante": "Carlos Andrade"
}

###
POST http://localhost:8000/api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "contato@empresa.com",
        "password": "senhaEmpresa!"
}
###

PUT http://localhost:8000/api/empresa/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "nome": "Empresa Atualizada",
        "username": "contato@empresa.com",
        "password": "novaSenhaEmpresa!",
        "telefone": "1144444444"
    },
    "cnpj": "12345678000199",
    "representante": "Ana Pereira"
}

###

PATCH http://localhost:8000/api/empresa/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "representante": "João Souza"
}

###

# 5.6 Deletar Empresa
DELETE http://localhost:8000/api/empresa/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}

###
POST http://localhost:8000/api/techleader/ HTTP/1.1
Content-Type: application/json

{
    "usuario": {
        "nome": "Novo TechLeader",
        "username": "tech@leader.com",
        "password": "senhaTech!",
        "telefone": "1155555555"
    },
    "codigo": "9999",
    "especialidade": "Backend"
}

###
PUT http://localhost:8000/api/techleader/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "usuario": {
        "nome": "TechLeader Atualizado",
        "username": "tech@leader.com",
        "password": "novaSenhaTech!",
        "telefone": "1166666666"
    },
    "codigo": "9999",
    "especialidade": "Fullstack"
}

###
PATCH http://localhost:8000/api/techleader/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "especialidade": "DevOps"
}

###
DELETE http://localhost:8000/api/techleader/2/ HTTP/1.1
Authorization: Bearer {{access_token}}
