
### 
GET {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

#############################################################

### Cria Area A
POST {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_A_nome}}"
}

### Cria Area B
POST {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_B_nome}}"
}

### Cria Area C
POST {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_C_nome}}"
}

### Cria Area D
POST {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_D_nome}}"
}

####################################################################

### PUT Area A
PUT {{url_raiz}}{{url_area}}{{area_fabrica_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_A_nome2}}",
    "ativa": "false"
}

### PUT Area B
PUT {{url_raiz}}{{url_area}}{{area_fabrica_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_B_nome2}}",
    "ativa": "false"
}

### PUT Area C
PUT {{url_raiz}}{{url_area}}{{area_fabrica_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_C_nome2}}",
    "ativa": "false"
}

### PUT Area D
PUT {{url_raiz}}{{url_area}}{{area_fabrica_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_D_nome2}}",
    "ativa": "false"
}

##########################################################################

### PATCH Area A
PATCH {{url_raiz}}{{url_area}}{{area_fabrica_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_A_nome}}",
    "ativa": "true"
}

### PATCH Area B
PATCH {{url_raiz}}{{url_area}}{{area_fabrica_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_B_nome}}",
    "ativa": "true"
}

### PATCH Area C
PATCH {{url_raiz}}{{url_area}}{{area_fabrica_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_C_nome}}",
    "ativa": "true"
}

### PATCH Area D
PATCH {{url_raiz}}{{url_area}}{{area_fabrica_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{area_fabrica_D_nome}}",
    "ativa": "true"
}


#########################################################################

### DELETE Area A
DELETE {{url_raiz}}{{url_area}}{{area_fabrica_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### DELETE Area B
DELETE {{url_raiz}}{{url_area}}{{area_fabrica_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### DELETE Area C
DELETE {{url_raiz}}{{url_area}}{{area_fabrica_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### DELETE Area D
DELETE {{url_raiz}}{{url_area}}{{area_fabrica_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}