
### Lista workshops
GET {{url_raiz}}{{url_workshop}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### Pega workshops
GET {{url_raiz}}{{url_workshop}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### Pega workshops
GET {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### Atribuir desempenho Participante A como Admin
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "usuario_id": "{{participante_A_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_A_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

### Atribuir desempenho Participante A como Instrutor
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{excecao_A_token}}

{
    "usuario_id": "{{participante_B_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_A_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

### Atribuir desempenho Participante B como Admin
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "usuario_id": "{{participante_B_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_B_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

### Atribuir desempenho Participante B como Instrutor
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{excecao_A_id}}

{
    "usuario_id": "{{participante_B_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_B_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

### Atribuir desempenho Participante C como Admin
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "usuario_id": "{{participante_C_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_C_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

### Atribuir desempenho Participante C como Instrutor
POST {{url_raiz}}{{url_desempenho}} HTTP/1.1
Content-Type: application/json
Authorization: {{excecao_A_id}}

{
    "usuario_id": "{{participante_C_id}}",
    "workshop": "{{workshop_A_id}}",
    "desempenho": "{{desempenho_classificacao5}}",
    "comentario": "{{desempenho_comentario5}}",
    "especialidade": "{{tecnologia_C_id}}",
    "aprovado": true,
    "classificacao": "{{desempenho_classificacao5}}",
    "experiencia": "{{desempenho_experiencia5}}"
}

