@url_raiz = http://localhost:8000/
@url_tecnologia = api/tecnologia/
@url_area = api/area_fabrica/
@url_imersao = api/imersao/
@url_formulario = api/formulario_inscricao/
@url_interesse = api/interesse_area/
###
@participante_A_username = pedro.silva@academico.com
@participante_A_password = Senha123
@participante_B_username = joao.pereira@academico.com
@participante_B_password = Senha123
@admin_username = admin@exsample.com
@admin_password = senhaSupesrSegura123
@access_token_admin = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMTg0Nzc4LCJpYXQiOjE3NTExODI5NzgsImp0aSI6ImVhMzg4YmM1YTA0MDRiOTRhODIyODMwMjhhZDA4Mjc1IiwidXNlcl9pZCI6MSwiaWQiOjEsIm5vbWUiOiJBZG1pbmlzdHJhZG9yIEdlcmFsIiwiZW1haWwiOiJhZG1pbkBleHNhbXBsZS5jb20iLCJ0aXBvX3VzdWFyaW8iOiJBRE1JTiJ9.ND8ayiMQTo6ZemLOVt5DoD7LFLJ_UBUko1ViwmCuIQc
@access_token_participanteA = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMTg0NzQ3LCJpYXQiOjE3NTExODI5NDcsImp0aSI6ImFlMzgyOWQ4ZjEyMjQ5NjM4MDJkZDBmZTdlNWYwNDBhIiwidXNlcl9pZCI6MiwiaWQiOjIsIm5vbWUiOiJQZWRybyBTaWx2YSIsImVtYWlsIjoicGVkcm8uc2lsdmFAYWNhZGVtaWNvLmNvbSIsInRpcG9fdXN1YXJpbyI6IlBBUlQifQ.O3cFVNYDLvCCtjqkDfudKdPLKiBSjz-M8ew51OOCqos
@access_token_participanteB = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMTg0NzYxLCJpYXQiOjE3NTExODI5NjEsImp0aSI6IjAwY2YzNmY0ZjgxNTRkM2E5YWFiZjIzOGJiN2QwNjY5IiwidXNlcl9pZCI6MywiaWQiOjMsIm5vbWUiOiJKb1x1MDBlM28gUGVyZWlyYSIsImVtYWlsIjoiam9hby5wZXJlaXJhQGFjYWRlbWljby5jb20iLCJ0aXBvX3VzdWFyaW8iOiJQQVJUIn0.CfVFjgLB2MOnPqXSIx6nejtF56FsdWYEE2UuL-QWsQI





### Faz login de admin para fazer crud de formularios
POST {{url_raiz}}api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "{{admin_username}}",
    "password": "{{admin_password}}"
}

### Faz login de Participante A para enviar requisicao, pois o usuario q mandar o request, vai assinar o formulario
POST {{url_raiz}}api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "{{participante_A_username}}",
    "password": "{{participante_A_password}}"
}

### Faz login de Participante A para enviar requisicao, pois o usuario q mandar o request, vai assinar o formulario
POST {{url_raiz}}api/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "{{participante_B_username}}",
    "password": "{{participante_B_password}}"
}


###
GET {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_interesse}} HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}


###
GET {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}


### 
GET {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}


### 
POST {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_participanteA}}


{    
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ],
    "outras_tech": [
        {
            "nome": "GoLang"
        },
        {
            "nome": "ObjC"
        } 
    ]
}

### 
POST {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_participanteB}}


{    
    "tecnologias": [3, 2],  
    "primeira_opcao": 2, 
    "segunda_opcao": 3,  
    "interesses": [       
        {
            "area": 3,  
            "nivel": 5  
        },
        {
            "area": 1,
            "nivel": 4
        }
    ]
}

### Apenas Admin
PUT {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}


{    
    "id_usuario": 2,
    "imersao": 1,
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ]
}

### Apenas admin
PATCH {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}


{    
    "id_usuario": 2,
    "imersao": 1,
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ]
}

### Apenas admin
DELETE  {{url_raiz}}{{url_formulario}}10/ HTTP/1.1
Content-Type: application/json
Authorization: {{access_token_admin}}