
###
GET {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_area}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json


###
GET {{url_raiz}}{{url_interesse}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}


###
GET {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}


### 
GET {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

############################################################

### 
POST {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{participante_A_token}}


{
    "tecnologias": ["{{tecnologia_A_id}}", "{{tecnologia_B_id}}"],  
    "primeira_opcao": "{{area_fabrica_A_id}}", 
    "segunda_opcao": "{{area_fabrica_B_id}}",  
    "interesses": [       
        {
            "area": "{{area_fabrica_A_id}}",  
            "nivel": 5  
        },
        {
            "area": "{{area_fabrica_B_id}}",
            "nivel": 4
        }
    ]
}

### 
POST {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{participante_B_token}}

{
    "tecnologias": ["{{tecnologia_C_id}}", "{{tecnologia_D_id}}"],  
    "primeira_opcao": "{{area_fabrica_C_id}}", 
    "segunda_opcao": "{{area_fabrica_B_id}}",  
    "interesses": [       
        {
            "area": "{{area_fabrica_C_id}}",  
            "nivel": 5  
        },
        {
            "area": "{{area_fabrica_B_id}}",
            "nivel": 4
        }
    ],
    "outras_tech": [
        {
            "nome": "{{formulario_B_outras_tech1}}"
        },
        {
            "nome": "{{formulario_B_outras_tech2}}"
        } 
    ]
}

### 
POST {{url_raiz}}{{url_formulario}} HTTP/1.1
Content-Type: application/json
Authorization: {{participante_C_token}}

{
    "tecnologias": ["{{tecnologia_A_id}}", "{{tecnologia_D_id}}"],  
    "primeira_opcao": "{{area_fabrica_A_id}}", 
    "segunda_opcao": "{{area_fabrica_C_id}}",  
    "interesses": [       
        {
            "area": "{{area_fabrica_A_id}}",  
            "nivel": 5  
        },
        {
            "area": "{{area_fabrica_C_id}}",
            "nivel": 4
        }
    ],
    "outras_tech": [
        {
            "nome": "{{formulario_C_outras_tech1}}"
        },
        {
            "nome": "{{formulario_C_outras_tech2}}"
        } 
    ]
}

### Apenas Admin
PUT {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}


{    
    "id_usuario": 2,
    "imersao": 1,
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ]
}

### Apenas admin
PATCH {{url_raiz}}{{url_formulario}}1/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}


{    
    "id_usuario": 2,
    "imersao": 1,
    "tecnologias": [1, 2],  
    "primeira_opcao": 1, 
    "segunda_opcao": 2,  
    "interesses": [       
        {
            "area": 1,  
            "nivel": 5  
        },
        {
            "area": 2,
            "nivel": 4
        }
    ]
}

### Apenas admin
DELETE  {{url_raiz}}{{url_formulario}}10/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}