
### Busca as iterações disponíveis para a imersao
GET {{url_raiz}}{{url_iteracao}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

### Busca as imersões
GET {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}


### Tenta criar imersão vazia
POST {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

##########################################################

### Cria Imersão A junto com Iteração A
POST {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "ano": "{{iteracao_A_ano}}",
    "semestre": "{{iteracao_A_semestre}}"
}

### Cria Imersão B assinalando a Iteração B
POST {{url_raiz}}{{url_imersao}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "iteracao": "{{iteracao_B_id}}"
}

#############################################################

###
GET {{url_raiz}}{{url_imersao}}{{imersao_A_id}}/ HTTP/1.1
Content-Type: application/json

###
GET {{url_raiz}}{{url_imersao}}{{imersao_B_id}}/ HTTP/1.1
Content-Type: application/json

###############################################################

###
PUT {{url_raiz}}{{url_imersao}}{{imersao_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "ano": "{{iteracao_A_ano}}",
    "semestre": "{{iteracao_A_semestre}}"
}

###
PUT {{url_raiz}}{{url_imersao}}{{imersao_B_id}}/ HTTP/1.1
Content-Type: application/json

{
    "iteracao": "{{iteracao_A_id}}"
}

############################################################

###
PUT {{url_raiz}}{{url_imersao}}{{imersao_A_id}}/ HTTP/1.1
Content-Type: application/json

{
    "iteracao": "{{iteracao_B_id}}"
}

###
PUT {{url_raiz}}{{url_imersao}}{{imersao_B_id}}/ HTTP/1.1
Content-Type: application/json

{
    "iteracao": "{{iteracao_A_id}}"
}

#################################################################

###
PATCH {{url_raiz}}{{url_imersao}}{{imersao_A_id}}/ HTTP/1.1
Content-Type: application/json

{
    "iteracao": "{{iteracao_A_id}}"
}

###
PATCH {{url_raiz}}{{url_imersao}}{{imersao_B_id}}/ HTTP/1.1
Content-Type: application/json

{
    "iteracao": "{{iteracao_B_id}}"
}

###################################################################

###
DELETE {{url_raiz}}{{url_imersao}}{{imersao_A_id}}/ HTTP/1.1
Content-Type: application/json

###
DELETE {{url_raiz}}{{url_imersao}}{{imersao_B_id}}/ HTTP/1.1
Content-Type: application/json
