@url_raiz = http://localhost:8000/


###
GET {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

############################################################

### POST Tecnologia A
POST {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_A_nome}}"
}

### POST Tecnologia B
POST {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_B_nome}}"
}

### POST Tecnologia C
POST {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_C_nome}}"
}

### POST Tecnologia D
POST {{url_raiz}}{{url_tecnologia}} HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_D_nome}}"
}

#########################################################

### PUT Tecnologia A
PUT {{url_raiz}}{{url_tecnologia}}{{tecnologia_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_A_nome2}}",
    "ativa": "false"
}

### PUT  Tecnologia B
PUT {{url_raiz}}{{url_tecnologia}}{{tecnologia_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_B_nome2}}",
    "ativa": "false"
}

### PUT Tecnologia C
PUT {{url_raiz}}{{url_tecnologia}}{{tecnologia_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_C_nome2}}",
    "ativa": "false"
}

### PUT Tecnologia D
PUT {{url_raiz}}{{url_tecnologia}}{{tecnologia_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_D_nome2}}",
    "ativa": "false"
}



##########################################################################

###
PATCH {{url_raiz}}{{url_tecnologia}}{{tecnologia_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{techleader_A_nome}}",
    "ativa": "true"
}

###
PATCH {{url_raiz}}{{url_tecnologia}}{{tecnologia_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_B_nome}}",
    "ativa": "true"
}

###
PATCH {{url_raiz}}{{url_tecnologia}}{{tecnologia_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_C_nome}}",
    "ativa": "true"
}

###
PATCH {{url_raiz}}{{url_tecnologia}}{{tecnologia_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

{
    "nome": "{{tecnologia_D_nome}}",
    "ativa": "true"
}

###################################################################

###
DELETE {{url_raiz}}{{url_tecnologia}}{{tecnologia_A_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

###
DELETE {{url_raiz}}{{url_tecnologia}}{{tecnologia_B_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

###
DELETE {{url_raiz}}{{url_tecnologia}}{{tecnologia_C_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}

###
DELETE {{url_raiz}}{{url_tecnologia}}{{tecnologia_D_id}}/ HTTP/1.1
Content-Type: application/json
Authorization: {{admin_token}}