# Generated by Django 5.1.7 on 2025-03-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False)),
                ('nome_de_usuario', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('telefone', models.IntegerField(default='', max_length=11)),
            ],
        ),
    ]
