# Generated by Django 5.1.7 on 2025-04-02 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(help_text='Digite seu nome completo sem abrevições', max_length=120, unique=True, verbose_name='Nome completo do usuário')),
                ('cpf', models.CharField(help_text='Digite apenas números (11 dígitos).', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='CPF deve conter exatamente 11 dígitos numéricos')], verbose_name='CPF')),
                ('username', models.EmailField(help_text='E-mail para autenticar usuário', max_length=254, unique=True, verbose_name='E-mail do usuário')),
                ('email_institucional', models.EmailField(help_text='E-mail institucional para permitir ingresso na fábrica de software', max_length=254, unique=True, verbose_name='Email Institucional')),
                ('rgm', models.CharField(help_text='RGM ativo para ingresso na fábrica de software', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='CPF deve conter exatamente 11 dígitos numéricos')], verbose_name='Registro Geral de Matrícula da Instituição')),
                ('telefone', models.CharField(blank=True, help_text='Número de telefone para contacto', max_length=15, null=True, verbose_name='Número de Telefone')),
                ('genero', models.CharField(blank=True, choices=[('NI', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Não aplicável')], default='NI', help_text='Selecione a opção que melhor representa sua identidade de gênero. ', max_length=2, null=True, verbose_name='Gênero')),
                ('curso', models.CharField(blank=True, choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('CC', 'Ciência da Computação'), ('SI', 'Sistemas para Internet'), ('CD', 'Ciência de Dados'), ('OTR', 'Outros')], help_text='Selecione o curso conforme sua matrícula ativa', max_length=3, null=True, verbose_name='Curso')),
                ('cargo', models.CharField(blank=True, choices=[('GESTOR', 'Gestor'), ('IMERSIONISTA', 'Imersionista'), ('NOVATO', 'Novato'), ('TECH_LEADER', 'Tech Leader'), ('VETERANO', 'Veterano')], help_text='Selecione seu cargo na Fábrica Software', max_length=15, null=True, verbose_name='Cargo')),
                ('ingresso_fab', models.DateField(blank=True, help_text='', null=True, verbose_name='Data de ingresso na Fábrica de Software')),
                ('setor', models.CharField(blank=True, choices=[('GESTAO', 'Gestão'), ('BACK', 'Back-end'), ('DADOS', 'Dados'), ('DEVOPS', 'DevOps'), ('FRONT', 'Front-end'), ('IA', 'Inteligência Artificial'), ('JOGOS', 'Jogos'), ('MOBILE', 'Mobile'), ('PO', 'Product Owner'), ('QA', 'Quality Assurance'), ('UIUX', 'UI/UX')], help_text='Em qual time você atuará? Essa informação nos ajuda a direcionar seus acessos e recursos. Se atuar em múltiplos setores, escolha o principal.', max_length=23, null=True, verbose_name='Setor')),
                ('situacao', models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ESTAGIANDO', 'Estagiando')], help_text='Situações: ATIVO, INATIVO, ESTAGIANDO', max_length=10, null=True, verbose_name='Situação')),
                ('is_bolsista', models.BooleanField(default=False, verbose_name='É bolsista?')),
                ('is_estagiario', models.BooleanField(default=False, verbose_name='É estagiário?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do usuário')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização do usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado de conta ativa ou não')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Estado de staff ativo ou não')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
    ]
