# Generated by Django 5.1.7 on 2025-04-03 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_usuario_ingresso_fab'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='projetosEntregues',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de projetos concluídos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='termosAceitos',
            field=models.BooleanField(default=False, help_text='Aceitou os termos de uso do sistema'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('GESTOR', 'Gestor'), ('IMERSIONISTA', 'Imersionista'), ('NOVATO', 'Novato'), ('TECH_LEADER', 'Tech Leader'), ('VETERANO', 'Veterano')], help_text='Cargo na Fábrica de Software', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(help_text='Apenas números (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='CPF deve ter exatamente 11 dígitos')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('CC', 'Ciência da Computação'), ('SI', 'Sistemas para Internet'), ('CD', 'Ciência de Dados'), ('OTR', 'Outros')], help_text='Curso matriculado', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, help_text='Última atualização'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de registro no sistema'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_institucional',
            field=models.EmailField(help_text='E-mail acadêmico/institucional', max_length=254, unique=True, verbose_name='E-mail institucional'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('NI', 'Não informado'), ('M', 'Masculino'), ('F', 'Feminino'), ('NA', 'Não aplicável')], default='NI', help_text='Identidade de gênero', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ingresso_fab',
            field=models.DateField(blank=True, help_text='Data de entrada na Fábrica', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Conta ativa/inativa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_bolsista',
            field=models.BooleanField(default=False, help_text='Indica se é bolsista'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_estagiario',
            field=models.BooleanField(default=False, help_text='Indica se é estagiário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Acesso ao admin'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(help_text='Nome completo sem abreviações', max_length=120, unique=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rgm',
            field=models.CharField(help_text='Registro Geral de Matrícula', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='RGM deve ter exatamente 8 dígitos')], verbose_name='RGM'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, choices=[('GESTAO', 'Gestão'), ('BACK', 'Back-end'), ('DADOS', 'Dados'), ('DEVOPS', 'DevOps'), ('FRONT', 'Front-end'), ('IA', 'Inteligência Artificial'), ('JOGOS', 'Jogos'), ('MOBILE', 'Mobile'), ('PO', 'Product Owner'), ('QA', 'Quality Assurance'), ('UIUX', 'UI/UX')], help_text='Área de atuação principal', max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='situacao',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('ESTAGIANDO', 'Estagiando')], help_text='Situação acadêmica', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número para contato', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(help_text='E-mail principal para login', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('termosAceitos', True)), name='termos_aceitos_obrigatorio', violation_error_message='Termos de uso devem ser aceitos para registro.'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
