# Generated by Django 5.1.7 on 2025-04-16 22:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_usuario_options_usuario_projetosentregues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Apenas números (14 dígitos)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', message='CNPJ deve ter exatamente 14 dígitos')], verbose_name='CNPJ')),
                ('representante', models.CharField(help_text='Pessoa que representa as decisões da empresa', max_length=250, verbose_name='Representante da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'permissions': [('ver_todas_empresas', 'Pode ver todos os participantes')],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('CC', 'Ciência da Computação'), ('SI', 'Sistemas para Internet'), ('CD', 'Ciência de Dados'), ('OTR', 'Outros')], help_text='Curso matriculado', max_length=3, null=True)),
                ('cpf', models.CharField(help_text='Apenas números (11 dígitos)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='CPF deve ter exatamente 11 dígitos')], verbose_name='CPF')),
                ('email_institucional', models.EmailField(help_text='E-mail acadêmico/institucional', max_length=254, unique=True, verbose_name='E-mail institucional')),
                ('ingresso_fab', models.DateField(auto_now_add=True, help_text='Data de entrada na Fábrica')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'permissions': [('ver_todos_participantes', 'Pode ver todos os participantes')],
            },
        ),
        migrations.CreateModel(
            name='TechLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Registro Geral sem pontos ou traços', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='Código deve conter apenas números')], verbose_name='Código único que identifica Tech Leader')),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de início como Tech Leader')),
                ('especialidade', models.CharField(help_text='Área de especialidade técnica', max_length=100)),
            ],
            options={
                'verbose_name': 'Tech Leader',
                'verbose_name_plural': 'Tech Leaders',
            },
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='termos_aceitos_obrigatorio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email_institucional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ingresso_fab',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_bolsista',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_estagiario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='projetosEntregues',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rgm',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='termosAceitos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PART', 'Participante'), ('EMP', 'Empresa'), ('TECH', 'Tech Leader'), ('ND', 'Não Definido')], default='ND', help_text='Tipo de usuário no sistema', max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(help_text='Nome completo sem abreviações', max_length=120, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techleader',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='techleader', to=settings.AUTH_USER_MODEL),
        ),
    ]
