# Generated by Django 5.1.7 on 2025-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_usuarios_delete_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=40, null=True, verbose_name='Gênero'),
        ),
    ]
