# Generated by Django 5.1.7 on 2025-04-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_empresa_participante_techleader_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techleader',
            options={'permissions': [('ver_todos_techleaders', 'Pode ver todos os tech leaders')], 'verbose_name': 'Tech Leader', 'verbose_name_plural': 'Tech Leaders'},
        ),
    ]
