# Generated by Django 5.1.7 on 2025-03-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_usuarios_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Institucional'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Telefone'),
        ),
    ]
