# Generated by Django 5.1.7 on 2025-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_participante_outro_curso_participante_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(help_text='E-mail principal para login', max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
