# Generated by Django 5.1.7 on 2025-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_alter_usuarios_email_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail do usuário'),
        ),
    ]
