# Generated by Django 5.1.7 on 2025-04-25 21:11

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='rgm',
            field=encrypted_model_fields.fields.EncryptedCharField(default=None, help_text='Apenas números (8 dígitos)', unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='RGM deve ter exatamente 8 dígitos')], verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Excecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Motivo da exceção', max_length=255)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de início da exceção')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excecao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extensionistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensionista', to='api_rest.excecao')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensionista', to='api_rest.participante')),
            ],
        ),
    ]
