# Generated by Django 5.1.7 on 2025-04-26 10:53

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_participante_rgm_excecao_extensionistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='rgm',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Apenas números (8 dígitos)', unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='RGM deve ter exatamente 8 dígitos')], verbose_name='RGM'),
        ),
    ]
