# Generated by Django 5.2 on 2025-04-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_alter_participante_rgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excecao',
            options={'permissions': [('ver_todas_excecoes', 'Pode ver todas as exceções')], 'verbose_name': 'Exceção', 'verbose_name_plural': 'Exceções'},
        ),
        migrations.CreateModel(
            name='Extensionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterano', models.BooleanField(default=False, help_text='Indica se o extensionista é veterano')),
                ('excecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionista', to='api_rest.excecao')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionista', to='api_rest.participante')),
            ],
            options={
                'verbose_name': 'Extensionista',
                'verbose_name_plural': 'Extensionistas',
                'permissions': [('ver_todos_extensionistas', 'Pode ver todos os extensionistas')],
            },
        ),
        migrations.DeleteModel(
            name='Extensionistas',
        ),
    ]
