# Generated by Django 5.2 on 2025-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_alter_excecao_options_extensionista_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('cpf',), name='unique_cpf'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('rgm',), name='unique_rgm'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('email_institucional',), name='unique_email'),
        ),
    ]
