# Generated by Django 5.2 on 2025-05-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_participante_unique_cpf_participante_unique_rgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cpf_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='email_institucional_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='rgm_hash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
