# Generated by Django 5.2 on 2025-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0012_participante_cpf_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='techleader',
            name='codigo_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email_institucional_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='rgm_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
