# Generated by Django 5.2 on 2025-05-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0013_empresa_cnpj_hash_techleader_codigo_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj_hash',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PART', 'Participante'), ('EMP', 'Empresa'), ('TECH', 'Tech Leader'), ('EXC', 'Exceção'), ('ND', 'Não Definido')], default='ND', help_text='Tipo de usuário no sistema', max_length=5),
        ),
    ]
