# Generated by Django 5.2 on 2025-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0015_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Já existe um usuário com esse username'}, help_text='E-mail principal para login', max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
