# Generated by Django 5.2 on 2025-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0016_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(error_messages={'unique': 'Este usuário já está cadastrado'}, help_text='E-mail principal para login', max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
