# Generated by Django 5.2 on 2025-06-02 17:18

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0017_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participante',
            name='unique_email',
        ),
        migrations.AlterField(
            model_name='extensionista',
            name='excecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionista_excecao', to='api_rest.excecao'),
        ),
        migrations.AlterField(
            model_name='extensionista',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensionista_participante', to='api_rest.participante'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email_institucional',
            field=encrypted_model_fields.fields.EncryptedEmailField(help_text='E-mail acadêmico/institucional', verbose_name='E-mail institucional'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('email_institucional__isnull', False)), fields=('email_institucional',), name='email_institucional_not_null_unique'),
        ),
    ]
