# Generated by Django 5.2 on 2025-06-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0018_remove_participante_unique_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participante',
            name='email_institucional_not_null_unique',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='email_institucional',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='email_institucional_hash',
        ),
    ]
