# Generated by Django 5.2 on 2025-06-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0019_remove_participante_email_institucional_not_null_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
    ]
