# Generated by Django 5.2 on 2025-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0020_remove_usuario_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techleader',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Área de especialidade técnica', max_length=100, null=True),
        ),
    ]
