# Generated by Django 5.2 on 2025-07-07 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0021_alter_techleader_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Cargo ou função do membro dentro deste projeto', max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', help_text='Status do membro nesta equipe específica', max_length=20)),
                ('extensionista', models.ForeignKey(help_text='Extensionista que faz parte da equipe', on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='api_rest.extensionista')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros das Equipes',
                'ordering': ['projeto', 'extensionista'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome oficial do projeto', max_length=250)),
                ('descricao', models.TextField(help_text='Descrição detalhada do escopo e objetivos do projeto')),
                ('area', models.CharField(help_text='Área de negócio ou departamento ao qual o projeto pertence', max_length=150)),
                ('data_prazo', models.DateField(help_text='Prazo final para a conclusão do projeto')),
                ('data_entrega', models.DateField(blank=True, help_text='Data em que o projeto foi efetivamente entregue (preencher ao concluir)', null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='ativo', help_text='Status atual do projeto', max_length=20)),
                ('etapa_atual', models.CharField(choices=[('planejamento', 'Planejamento'), ('desenvolvimento', 'Desenvolvimento'), ('testes', 'Testes'), ('implantacao', 'Implantação'), ('concluido', 'Concluído')], default='planejamento', help_text='Etapa em que o projeto se encontra', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais, anotações e pontos de atenção', null=True)),
                ('progresso', models.PositiveIntegerField(default=0, help_text='Progresso do projeto em porcentagem (de 0 a 100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa cliente para a qual o projeto está sendo desenvolvido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_contratados', to='api_rest.empresa')),
                ('equipe', models.ManyToManyField(blank=True, related_name='projetos_participantes', through='projetos.MembroEquipe', to='api_rest.extensionista')),
                ('techleader', models.ForeignKey(blank=True, help_text='Tech Leader responsável pelo projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_liderados', to='api_rest.techleader')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_prazo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto ao qual o membro está alocado', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='projetos.projeto'),
        ),
        migrations.AlterUniqueTogether(
            name='membroequipe',
            unique_together={('projeto', 'extensionista')},
        ),
    ]
