# Generated by Django 5.2 on 2025-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imersao', '0002_emailsadmins_emailsfixos_emailsparticipantes'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membroequipe',
            name='cargo',
        ),
        migrations.AddField(
            model_name='membroequipe',
            name='cargo',
            field=models.ManyToManyField(help_text='Area da Fábrica referente ao cargo ou função do membro dentro deste projeto', related_name='cargos', to='imersao.areafabrica'),
        ),
    ]
